In [2]:
import numpy as np
# arr = np.array([1,2,3,4,5])
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(np.__version__)

2.2.6


In [4]:
arr = np.array([[1,2,3,4,5], [5,6,7,8,9]])
print(arr)
print(type(arr))

[[1 2 3 4 5]
 [5 6 7 8 9]]
<class 'numpy.ndarray'>


In [5]:
arr = np.array([[[1,2,3,4,5], [5,6,7,8,9]], [[1,2,3,4,5,], [5,6,7,8,9]]])
print(arr)
print(type(arr))

[[[1 2 3 4 5]
  [5 6 7 8 9]]

 [[1 2 3 4 5]
  [5 6 7 8 9]]]
<class 'numpy.ndarray'>


In [6]:
print(arr.ndim)

3


In [7]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [8]:
arr = np.array([1,2,3,4,5])
print(arr[1]+arr[1])

4


In [9]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr[0,1] - arr[1, 3])

-6


In [10]:
arr = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [5,6,7,8]]])
print(arr[0,1,2] - arr[1, 1, -2])

0


In [11]:
arr = np.array([1,2,3,4,5])
print(arr[1:])
print(arr[:3])
print(arr[-5:-2:2])
print(arr[::-2])

[2 3 4 5]
[1 2 3]
[1 3]
[5 3 1]


In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print(arr[0:1], 2)
print(arr[0:2, 0:3])

[[1 2 3 4 5]] 2
[[1 2 3]
 [6 7 8]]


In [13]:
print(arr.dtype)

int64


In [14]:
arr = np.array(['banana', 'apple', 'chut'])
print(arr.dtype)

<U6


In [15]:
arr = np.array([1,a,3,4], dtype = "i4")
print(arr)
print(arr.dtype)

NameError: name 'a' is not defined

In [ ]:
arr = np.array([0, 1.3, 1.4, 1.5])
newarr = arr.astype(int)
print(newarr.dtype)
print(newarr)

int64
[0 1 1 1]


In [ ]:
newarr = arr.astype(bool)
print(newarr.dtype)
print(newarr)

bool
[False  True  True  True]


In [ ]:
new = arr.copy()
arr[0] = 8
print(new)
print(arr)

[0.  1.3 1.4 1.5]
[8.  1.3 1.4 1.5]


In [ ]:
new = arr.view()
new[0] = 8

print(new)
print(arr)

[8.  1.3 1.4 1.5]
[8.  1.3 1.4 1.5]


In [ ]:
arr = np.array([1,2,3,4,5])

x = arr.view()
y = arr.copy()

print(x.base)
print(y.base)

[1 2 3 4 5]
None


In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)

(2, 4)


In [16]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [29]:
arr = np.array([1,2,3,4, 5, 6, 7, 8, 9, 0, 11, 12])
newarr = arr.reshape(4, 3)
newarr = arr.reshape(2,3,2)
newarr = arr.reshape(2,3,-1)
newarr = arr.reshape(-1)
print(newarr)
print(newarr.ndim)
print(newarr.base)
for x in newarr:
  print(x)

[ 1  2  3  4  5  6  7  8  9  0 11 12]
1
[ 1  2  3  4  5  6  7  8  9  0 11 12]
1
2
3
4
5
6
7
8
9
0
11
12


In [31]:
newarr = arr.reshape(2,3,-1)
for x in newarr:
  print(x)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9  0]
 [11 12]]


In [36]:
arr = np.array([[[1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4]]])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [39]:
for x in np.nditer(arr[0, :, ::2]):
  print(x)

1
3
1
3


In [45]:
arr = np.array([6,4,5,78,9])
for x, idx in np.ndenumerate(arr):
  print(x, idx)

(0,) 6
(1,) 4
(2,) 5
(3,) 78
(4,) 9
