In [3]:
import numpy as np
# arr = np.array([1,2,3,4,5])
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
print(np.__version__)

2.2.6


In [4]:
arr = np.array([[1,2,3,4,5], [5,6,7,8,9]])
print(arr)
print(type(arr))

[[1 2 3 4 5]
 [5 6 7 8 9]]
<class 'numpy.ndarray'>


In [8]:
arr = np.array([[[1,2,3,4,5], [5,6,7,8,9]], [[1,2,3,4,5,], [5,6,7,8,9]]])
print(arr)
print(type(arr))

[[[1 2 3 4 5]
  [5 6 7 8 9]]

 [[1 2 3 4 5]
  [5 6 7 8 9]]]
<class 'numpy.ndarray'>


In [10]:
print(arr.ndim)

3


In [17]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [ ]:
arr = np.array([1,2,3,4,5])
