In [3]:
import numpy as np
# arr = np.array([1,2,3,4,5])
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
print(np.__version__)

2.2.6


In [4]:
arr = np.array([[1,2,3,4,5], [5,6,7,8,9]])
print(arr)
print(type(arr))

[[1 2 3 4 5]
 [5 6 7 8 9]]
<class 'numpy.ndarray'>


In [8]:
arr = np.array([[[1,2,3,4,5], [5,6,7,8,9]], [[1,2,3,4,5,], [5,6,7,8,9]]])
print(arr)
print(type(arr))

[[[1 2 3 4 5]
  [5 6 7 8 9]]

 [[1 2 3 4 5]
  [5 6 7 8 9]]]
<class 'numpy.ndarray'>


In [10]:
print(arr.ndim)

3


In [17]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [19]:
arr = np.array([1,2,3,4,5])
print(arr[1]+arr[1])

4


In [22]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr[0,1] - arr[1, 3])

-6


In [26]:
arr = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [5,6,7,8]]])
print(arr[0,1,2] - arr[1, 1, -2])

0


In [44]:
arr = np.array([1,2,3,4,5])
print(arr[1:])
print(arr[:3])
print(arr[-5:-2:2])
print(arr[::-2])

[2 3 4 5]
[1 2 3]
[1 3]
[5 3 1]


In [50]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print(arr[0:1], 2)
print(arr[0:2, 0:3])

[[1 2 3 4 5]] 2
[[1 2 3]
 [6 7 8]]
