In [4]:
## Splitting array and other stuff

import numpy as np
arr = np.array([[1,2,3,], [2,43,56], [4,6,8], [45,54,5], [453,453,5]])
newarr = np.array_split(arr, 3, axis =1)
print(arr)
print(newarr)


[[  1   2   3]
 [  2  43  56]
 [  4   6   8]
 [ 45  54   5]
 [453 453   5]]
[array([[  1],
       [  2],
       [  4],
       [ 45],
       [453]]), array([[  2],
       [ 43],
       [  6],
       [ 54],
       [453]]), array([[ 3],
       [56],
       [ 8],
       [ 5],
       [ 5]])]


In [5]:
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[  1],
       [  2],
       [  4],
       [ 45],
       [453]]), array([[  2],
       [ 43],
       [  6],
       [ 54],
       [453]]), array([[ 3],
       [56],
       [ 8],
       [ 5],
       [ 5]])]


In [7]:
import numpy as np 
arr = np.array([1,9,3,9,5,6,7,8,9,0])
x = np.where(arr == 9)
print(x);

(array([1, 3, 8]),)


In [8]:
x = np.where(arr%2 == 0)
print(x)

(array([5, 7, 9]),)


In [24]:
import numpy as np 

arr = np.array([0,1,2,3,4,5,6,7,8,9])
x = np.searchsorted(arr, 9, side = "right")
print(x)

10


In [28]:
import numpy as np

arr = np.array([6, 7, 8, 9, 10, 11, 12, 13, 14])

x = np.searchsorted(arr, 14, side='right')

print(x)

9


In [31]:
arr = np.array([2,4,6,8])
x = np.searchsorted(arr, [1,3,5,7])
print(x)

[0 1 2 3]
